project_id = "auujtzrbhfynilvygjcv"

[functions.create-payment]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.sribot-chat]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.weekly-newsletter]
verify_jwt = false
