// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikftyunzqllocvjjevag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZnR5dW56cWxsb2N2ampldmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDA4MDQsImV4cCI6MjA1OTYxNjgwNH0.2MBXos4fD1bJ8Bxttri9UdY1c2PVy9dDBcoIn0STzCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);