// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awtslwpsiearmicxrlhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dHNsd3BzaWVhcm1pY3hybGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDgzNzMsImV4cCI6MjA2NDA4NDM3M30.gqOCW3WDaaD8JiPnnTlgRyrWvfXUgQJin4Kp_mFPziQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);